apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-service-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: external-service-operator
  template:
    metadata:
      labels:
        name: external-service-operator
    spec:
      serviceAccountName: external-service-operator
      containers:
        - name: external-service-operator
          # Replace this with the built image name
          image: lablabs/external-service-operator:0.0.4
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "external-service-operator"
