apiVersion: v1
kind: Secret
metadata:
  name: external-service-operator-openstack
type: Opaque
data:
  # values in base64
  url: Zm9vYmFhcg==
  username: Zm9vYmFhcg==
  password: Zm9vYmFhcg==
  project: Zm9vYmFhcg==