apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ include "external-service.name" . }}
    helm.sh/chart: {{ include "external-service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/type: {{ .Values.type }}
subsets:
{{- if eq .Values.type "static" }}
- addresses:
  {{- range .Values.endpoints }}
  - ip: {{ . }}
  {{- end }}
{{- else }}
# Hack: Endpoints placeholder as notReadyAddresses
- notReadyAddresses:
  - ip: 0.0.0.1
{{- end }}
  ports:
  {{- range $name, $port := .Values.ports }}
  - name: {{ $name }}
    protocol: TCP
    port: {{ $port }}
  {{- end }}