apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ include "external-service.name" . }}
    helm.sh/chart: {{ include "external-service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/type: {{ .Values.type }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  {{- range $name, $port := .Values.ports }}
  - name: {{ $name }}
    protocol: TCP
    port: {{ $port }}
    targetPort: {{ $port }}
  {{- end }}